### ISSUE TITLE
Icons and sub menus 

### ISSUE THREAD

**Issue by metehan** [andreabenini/gnome-plugin.custom-menu-panel#1]
Icons and sub menus would be nice additions.

**Comment by andreabenini** [comment]
sub menus are already there but poorly documented, my fault :(
Take a look at:
https://github.com/andreabenini/gnome-plugin.custom-menu-panel/commit/7a9c85ee09dff5abbfe5c26dc606238bf2ede3c2
I've just updated the provided example to match your needs:
https://github.com/andreabenini/gnome-plugin.custom-menu-panel/blob/main/examples/.entries.json
