### ISSUE TITLE
[Question] Why is this extension outdated in the official extension repository?

### ISSUE THREAD

**Issue by salazarbarrera** [andreabenini/gnome-plugin.custom-menu-panel#5]
More than an issue this is just a question. Is there a reason why [the last version in gnome.org](https://extensions.gnome.org/extension/4295/custom-menu-panel/) is 2 while the current one is 4?

**Comment by andreabenini** [comment]
I really don't know :)
I guess I need to discuss with them to get the plugin updated in the portal too.. There's a broken CI/CD somewhere...
This is an active project and I constantly made changes to add new features or simply to keep it in sync with newer Gnome releases.
I use Arch in my daily desktop, to use the plugin with a rolling distro I always keep it up to date with newer gnome versions when they comes out.

**Comment by andreabenini** [comment]
Reapplied back again, hopefully it will be approved.
I'm using it daily with my local Gnome version, hopefully you'll be able to get it from official gnome extensions repo too.
I've just uploaded a fix related to selector status on startup
